#--***************************************************************************************
#    Title: demo/config/routes/dev/framework.yaml
#    Author: Symfony
#    Date: 2020
#    Code version: 1.5.1
#    Availability: https://github.com/symfony/demo
#
#**************************************************************************************/-->


_errors:
    resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
    prefix: /_error
