#--***************************************************************************************
#    Title: Verify Phone Numbers in Symfony 4 PHP with Authy and Twilio SMS
#    Author: Oluyemi Olususi
#    Date: 29-05-2019
#    Code version: 1
#    Availability: https://www.twilio.com/blog/verify-phone-numbers-in-symfony-4-php-with-authy-and-twilio-sms
#
#**************************************************************************************-->

app_login:
    path: /homepage
    controller: App\Controller\DefaultController::app
logout:
    path: /logout
send:
    path: /send
    controller: App\Controller\SecurityController::sendSms
verify_code2:
    path: /verify/code2
    controller: App\Controller\SecurityController::verifyCode2
verify_page2:
    path: /verify/page2
    controller: App\Controller\DefaultController::verifyPage2
loginVerify:
    path: /
    controller: App\Controller\SecurityController::loginVerify






  

