#--***************************************************************************************
#    Title: Verify Phone Numbers in Symfony 4 PHP with Authy and Twilio SMS
#    Author: Oluyemi Olususi
#    Date: 29-05-2019
#    Code version: 1
#    Availability: https://www.twilio.com/blog/verify-phone-numbers-in-symfony-4-php-with-authy-and-twilio-sms
#
#**************************************************************************************-->


#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
    path: /logout

  

